-- No-op.
--
-- This migration was originally generated as a `drizzle-kit generate` snapshot
-- from an empty schema while 0001..0011 already existed in the journal, so it
-- recreated every table and re-issued every ADD COLUMN. On a pre-existing dev
-- DB it had been marked applied before becoming a problem; on a fresh VPS
-- deploy drizzle iterates the whole journal and the duplicate CREATE TABLE
-- statements abort with "table already exists".
--
-- Drizzle's better-sqlite3 migrator gates replay by `created_at` (folderMillis
-- from _journal.json), not by hash, so neutering the SQL here does not cause
-- existing DBs (where lastDbMigration.created_at > 1779365664538) to rerun it.
-- Fresh DBs apply this file as a no-op and continue with 0013+.
SELECT 1;
